name: "Discord4Bukkit"
main: "net.pl3x.bukkit.discord4bukkit.D4BPlugin"
version: "${project.version}"
description: "Discord Bot for Bukkit Servers"
author: "BillyGalbreath"
api-version: "1.13"

commands:
  discord4bukkit:
    description: Controls the discord bot
    permission: command.discord4bukkit
    usage: /<command> (reload)
    aliases:
      - discordbot
      - d4b

permissions:
  command.discord4bukkit:
    description: Allows controlling the bot
    default: op
